### ISSUE TITLE
preview gets stuck and wont go away

### ISSUE THREAD

**Issue by keen-bean** [Previews-app/Previews#12]
**Describe the bug**
preview gets stuck and wont go away
it also sometimes just doesn't show preview unless I refresh page several times

**To Reproduce**
1. hover over twitch user on the left panel

**Expected behavior**
preview appears but goes away when I click anywhere else on the page

**Environment:**
 - OS: Windows 10 pro
 - Browser: chrome
 - Browser Version: 114.0.5735.90 (Official Build) (64-bit)
 - Extension Version: 8.4

**Additional context**
no

![image](https://github.com/Previews-app/Previews/assets/134891446/5ba67d19-bdff-499b-810a-9bde61524087)

**Comment by Previews-app** [comment]
duplicate https://github.com/Previews-app/Previews/issues/9
until i figure out what's happening if anything you mentioned happens you can switch to a different tab and come back to the twitch tab and it should purge a stuck preview or reset hover previews if a preview is not showing.
