### ISSUE TITLE
Facebook Sidebar Link Issue

### ISSUE THREAD

**Issue by blackpoolfc04** [Previews-app/Previews#13]
**Describe the bug**
Facebook gaming channels have quotation marks now. If you click the link it will take you to www.facebook.com/"DasMehdi" instead of www.facebook.com/DasMehdi

**Expected behaviour**
Takes you to the correct link

**Screenshots and videos**
![17 06 23_10 01 44   chrome   6019](https://github.com/Previews-app/Previews/assets/96628476/439466bd-c595-460f-ae09-5be97cf56dc0)

**Environment:**
 - OS: Windows 10
 - Browser: Chrome
 - Extension Version: v8.6

**Additional context**
I have tried to re-add the Facebook channel names to the extension but this didn't fix it.

**Comment by Previews-app** [comment]
try doing the "Clear browser's facebook-related site data and cookies" section in this, i think it will might fix your issue:
https://github.com/Previews-app/Previews/issues/2
reopen if issue persists.
