### ISSUE TITLE
Content Warning

### ISSUE THREAD

**Issue by CoderDayton** [Previews-app/Previews#14]
**Describe the bug**
Twitch previews won't load if the channel has content warnings. For example it will say "channel's content is intended for certain audiences".

**To Reproduce**
1. Hover over a channel with content warnings

**Expected behavior**
I would expect the stream to load like normal.

**Screenshots and videos**
![Screenshot](https://i.imgur.com/VbpmDSr.png)

**Environment:**
 - OS: Windows 11
 - Browser: Chrome
 - Browser Version: 114.0.5735.199
 - Extension Version: 8.7

**Comment by Previews-app** [comment]
as this is a legal issue on twitch, i cannot click the button for you.
however a workaround has been implemented a long time ago where if you hover the preview window with your mouse it will stay open for a short period of time allowing you to click the button, you only need to do this once per streamer ever, from what i have noticed, unless your local storage gets somehow reset or cleared.

so just hover over the preview and click the button.
