### ISSUE TITLE
Auto Refresh On Twitch Player Error BUG

### ISSUE THREAD

**Issue by Mishasama** [Previews-app/Previews#15]
**Describe the bug**
When watching VODs occurs a #2000 error, the extension will reload the player instead of refreshing the page. This will cause the playback progress to be lost, and you will have to watch from the beginning.

**To Reproduce**
1. Switch on "Auto Refresh On Twitch Player Error"
2. Watch a VOD
3. Occur a #2000 error

**Expected behavior**
It should be able to continue playing after reloading following the previous playback progress, rather than starting from the beginning.

**Screenshots and videos**
I can't record a video that I don't know when to start.

**Environment:**
 - OS: Windows 10
 - Browser: Chrome
 - Browser Version: 115.0.5790.110
 - Extension Version: 8.8

**Additional context**
Maybe you should remember the playback progress.

**Comment by Previews-app** [comment]
This unfortunately is a Twitch bug - you can see in code when you check the progress of the video element when it gets an error that it is reset to 0 so no matter what you do it will always resume playing from the start after an error.
You will need to file a bug report to Twitch. no use for me to fix something that they need to fix
