### ISSUE TITLE
Fast Forward

### ISSUE THREAD

**Issue by Lordminnion1** [Previews-app/Previews#18]
**Describe the bug**
Watching a twitch stream and I would have the Fast Forward button there but after about like 30 minutes sometimes less the Fast Forward button is gone. If I refresh it comes back but if I just watch again it disappears.

**To Reproduce**
I just watch any twitch stream and it does it

**Expected behavior**
To be able to skip forward on the twitch streams

**Screenshots and videos**
![opera_M1NtXAb7Ce](https://github.com/Previews-app/Previews/assets/131046828/6d04b6bc-7c4c-45af-a14c-8acbf626c6e6)
![opera_UaVwxCE8gl](https://github.com/Previews-app/Previews/assets/131046828/3c0de3cb-2ef3-4407-98ae-aa1d33a99192)

**Environment:**
 - OS: Windows 11
 - Browser: Opera GX
 - Browser Version: 104
 - Extension Version: 9.3
 - <any other variables you may see fit>

**Additional context**
Those screen shots I refreshed 1 page and it the fast forward button reappeared so I could show you, but it originally didn't have it there

**Comment by CreeperChief** [comment]
You might be using an outdated version of the plugin. [Check here](https://github.com/Previews-app/Previews/issues/10)

**Comment by Previews-app** [comment]
should be fixed already, reopen if persists.
if it happens again try to remember if something happened before it went away (like an ad).
