### ISSUE TITLE
Triggering a preview messes up your chat message

### ISSUE THREAD

**Issue by Halvencyon** [Previews-app/Previews#23]
**Describe the bug**
When you type in a chat and pop up a Twitch preview, the text cursor resets to the beginning of the line.

**To Reproduce**
1. Start typing in a chat
2. Mouse over any Twitch channel in your following list so a preview appears
3. Return to the chat
4. Your text cursor shifts to the beginning of the line, rather than where you left off typing

**Expected behavior**
I expect the text cursor to return to the position I was typing rather than back to the beginning of the text box.

**Screenshots and videos**
Below is me typing "Here is a message." without triggering a preview:
![Hereisamessage](https://github.com/Previews-app/Previews/assets/135398735/9e00ee12-4358-4906-b7e3-366a1c76c873)

Below is me interrupting my message halfway through. I type "Here is" then trigger a preview, then return to the chat to type "a 
message.":
![messageHereisa](https://github.com/Previews-app/Previews/assets/135398735/cdc47fa0-9356-4074-af34-4015d1e5cb08)

**Environment:**
 - OS: Windows 10
 - Browser: Chrome
 - Browser Version: 122.0.6261.95
 - Extension Version: 9.9

**Additional context**
I've never submitted a bug report before but this issue was bothering me enough to say something lol

**Comment by Previews-app** [comment]
same, when did this start?
also, seems that it only happens on twitch previews and not youtube previews.

**Comment by Halvencyon** [comment]
I believe it has been an issue in the past, was resolved, but has just recently come back. I cannot comment on YouTube since I don't use Previews there but I'm glad it's not an issue there

**Comment by Previews-app** [comment]
i meant the youtube previews when you hover over youtubers on your twitch sidebar (we have a feature for that).
it looks like twitch did something that messed it up, i didn't even know about last time.
if they fixed it last time they might fix it again this time, we'll wait a while to see if they fix it, if not.. i'll see what i can do.

**Comment by Previews-app** [comment]
looks like they fixed the cursor issue, closing for now.
