### ISSUE TITLE
Predictions Sniper is not working properly.

### ISSUE THREAD

**Issue by Mishasama** [Previews-app/Previews#24]
**Describe the bug**
Predictions Sniper cannot properly fill in the points to be put in and confirmed.

**To Reproduce**
Just watch the videos.

**Expected behavior**
Completion points inputs.

**Screenshots and videos**
If applicable, add screenshots and videos to help explain your problem.
![Video](https://github.com/Previews-app/Previews/assets/54498172/13f7038d-210d-4cef-9318-f20ef83fd2da)

https://github.com/Previews-app/Previews/assets/54498172/087e1785-8f12-42d2-aa0d-99b5f25fae63

**Environment:**
 - OS: Windows 10
 - Browser: Chrome
 - Browser Version: 123.0.6312.86
 - Extension Version: 10.0
 - <any other variables you may see fit>

**Additional context**
Recently, I've been having issues with Twitch. It used to work fine, but now it's not. Did something change with the Twitch page source code that could have caused this issue?

**Comment by Previews-app** [comment]
Yes, Twitch changed some stuff and made some bugs happen, some in the extension and some globally for everyone.
i guess something got bugged in the predictions sniper, ill investigate for the next version, seems to work sometimes and sometimes not. possibly related to language ill check.

Some of the other bugs that twitch added globally for everyone are in the sidebar when you hover your mouse in or out it would scroll to the opposite side of the sidebar and also the tooltip would have a white border around it.

**Comment by Previews-app** [comment]
Also, check if you get something in the console when it's trying to make a prediction (like when in the video).
might see an error originating from core.js (you will see the filename on the right) or maybe something with the text "APS:" with a date and a message

**Comment by Previews-app** [comment]
Issue fixed, version 10.1 waiting for approval.

**Comment by Mishasama** [comment]
Fixed confirmed.
