### ISSUE TITLE
Playback speed resets when buffering

### ISSUE THREAD

**Issue by pushkine** [Previews-app/Previews#25]
1. Speed up youtube video with the buttons added by the extension
2. Skip to somewhere in the video that is not loaded yet
3. Observe playback speed resets (sometimes it does, sometimes it doesn't)

**Comment by Previews-app** [comment]
Hi,

I see what you mean, the playback speed reset is intended to work like this for live broadcasts for when you reach the end of the playback (which causes a buffer to load the next sequence of the live), but should work differently when watching a video.

Will fix for next version.
Thanks.

**Comment by Previews-app** [comment]
fixed 10.2.
