### ISSUE TITLE
Contribution to translate

### ISSUE THREAD

**Issue by akawshi** [Previews-app/Previews#26]
I would like to translate app in Japanese. The app has already been translated into several languages by Google services, but it is not perfect.  
Can I find any way to get involved?

**Comment by Previews-app** [comment]
Hi,
Sure thing!

There are 2 language files for translations (about 400 entries total).
Please send an email or dm me on discord (I'm MQ) so i can send you the files alongside other info about them.

Appreciate the help!

**Comment by Previews-app** [comment]
i replied :)

**Comment by Previews-app** [comment]
I sent you some translations that need to be looked at again to make sure they are correct, and also 2 more entries that were in a different file.
Thanks for the help!
