### ISSUE TITLE
Predictions Sniper will show put 1 point into the poll even when it has no point.

### ISSUE THREAD

**Issue by Mishasama** [Previews-app/Previews#28]
**Describe the bug**
When there are no points available for betting (0 points), the notification will still show 1 point successfully bet.

**To Reproduce**
1. Enable Predictions Sniper
2. Watch a stream that running a prediction
3. Be sure you have no point

**Expected behavior**
It should state in the notification that the user does not have enough points to participate in the poll.

**Screenshots and videos**
![image](https://github.com/Previews-app/Previews/assets/54498172/25c10284-3679-441a-ade4-98c659b41516)

**Environment:**
 - OS: Windows 10
 - Browser: Chrome
 - Browser Version: 124.0.6367.91
 - Extension Version: 10.1
 - <any other variables you may see fit>

**Additional context**
<Add any other context about the problem here.> hmm...no.

**Comment by Previews-app** [comment]
fixed 10.2.
