### ISSUE TITLE
Custom buffer retention time for the fast-forward feature

### ISSUE THREAD

**Issue by Mishasama** [Previews-app/Previews#34]
When clicking this button in an environment with slow network speed, it often results in prolonged stalling. The actual situation is that the buffer is cleared, triggering the player to reconnect, and leading to difficulties in buffering.

If we could customize the buffer retention length in the settings, such as 500 milliseconds or 1~2 seconds, the situation would be greatly improved because the buffer would not be cleared, thus not triggering a reconnect.
But the exact amount to set is appropriate, this needs to be judged based on the user's own network conditions, so it cannot be fixed by hardcoding to a specific length, it must be set as a variable for the user to adjust the appropriate value by themselves.

**Comment by Previews-app** [comment]
No need, and it doesnt fit the feature. the feature is meant to make the player "reconnect".
To do what you are describing, Enable the "Seek Streams Using Keyboard Arrow Keys" feature and seek to the end (right arrow), it's designed not to trigger a reconnect at the end of the buffer and it puts playback at around 1 second before the end of the buffer.
You can also enable the "Playback speed controls" feature and fast wind forward and it will automatically reset to 1X playback speed when it reaches around 1 second from the end of the playback.
