### ISSUE TITLE
Clicking on a Favourite Channel no longer takes me to the channel and stays on previous page

### ISSUE THREAD

**Issue by Nerxxy** [Previews-app/Previews#36]
**Describe the bug**
Click on a favourite channel, for example on XQC the url will change to www.twitch.tv/xqc# but it wont change from the page i was already on.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have a Favourite Channel
2. Click on a Favourite channel
3. See URL change
4. See page not change to clicked Favourite Channel

**Expected behaviour**
Go to the Favourite Channel 

**Screenshots and videos**
![image](https://github.com/user-attachments/assets/1c7dfc01-087c-4cc2-ac00-918e7b9a4442)
Clearly see that im still on the home page

**Environment:**
 - OS: Windows 10
 - Browser: Firefox Nightly
 - Browser Version: 133.0b5 (64-bit)
 - Extension Version: 11.1
 - <any other variables you may see fit>

**Additional context** 
 The url has always had a # for me but it used to always just take me to the channel despite that.

Middle mouse clicking/opening in a new tab however does take me to the Favourite Channel.

**Comment by Previews-app** [comment]
Hi, try disabling ALL other extension even if you think they have no relation and then refresh your twitch tabs.
See if this fixed it, if it did you can enable them one by one to see what is causing it.

also try on normal firefox and not nightly.

**Comment by Nerxxy** [comment]
Ok i just tested what you said and it works fine on normal firefox, which is annoying since nightly is my daily driver, and i would rather not have to swap over bc of this minor issue, it was all working fine like 4 days ago.

Is there any particular reason for the # to be there?

**Comment by Previews-app** [comment]
Yes, it makes the page transition within the SPA without reloading the page.

**Comment by Nerxxy** [comment]
Ah ok, ig i just gotta wait for FF to fix it then :/ not too much of an issue, thanks for your time :)

**Comment by Previews-app** [comment]
No problem! im wondering if this issue will end up in the normal version.
Closing this for now, keep me posted.

**Comment by Nerxxy** [comment]
little update, First of all, i wasnt on nightly, that was my mistake, i was on Developer edition, Second of all, it also persists on FF Nightly 135.0a1 so yeah, its definitely an issue with early builds

**Comment by Nerxxy** [comment]
dont know when it was fixed but its been fixed since yesterday for me 

FF Dev 134.0b10 (aurora update channel, if that makes a difference)

**Comment by Previews-app** [comment]
yea firefox approved the new version 2 days ago.
