### ISSUE TITLE
Firefox early builds not transitioning to channels

### ISSUE THREAD

**Issue by Xanthognarh** [Previews-app/Previews#37]
**Describe the bug**
While this extension is active on twitch, i can't switch channels. Clicking on a channel changes the url to twitch.tv/NEWCHANNELNAME#, but nothing else happens. Everything works fine without the number sign in the url.

**To Reproduce**
1. Run Firefox Developer Edition 133.0b6 64-bit
2. Open any twitch.tv/CHANNEL
3. Click without hovering (no preview) on an other channel
4. The channel changes
5. Hover over an channel to open the preview
6. Click on any Channel
7. See error: URL changes to twitch.tv/NEWCHANNELNAME#

**Expected behavior**
A click on a channel shoud open twitch.tv/NEWCHANNELNAME instead of twitch.tv/NEWCHANNELNAME#

**Environment:**
 - OS: Win 10
 - Browser: Firefox
 - Browser Version: Developer Edition 133.0b6 64-bit
 - Extension Version: v11.1
 
**Additional context**
It works as expected with the extension disabled.

**Comment by Previews-app** [comment]
check [https://github.com/Previews-app/Previews/issues/36](https://github.com/Previews-app/Previews/issues/36)
It seems to be an issue in firefox early builds.
the # makes the page transition within the SPA without reloading the page and the # is supposed to disappear after transitioning.
leaving this open for now.

**Comment by Anno1986** [comment]
Hi,
Ii have the same problem with Release and Beta Versions.

- OS: Win 10
- Browser: Firefox
- Browser Version: _Release 133.0 64-bit_ and _Beta 134.0b4 64-bit_
- Extension Version: v11.4

**Comment by Previews-app** [comment]
looks like this seeped into the release..... i fixed it for now (v11.5) without the SPA transition until i can find a way to make it transition without reloading the page. leaving this open for now until i do. 11.5 will be available in the next few days.

**Comment by Previews-app** [comment]
found a way, fix on the way.
