### ISSUE TITLE
[Feature] Twitch favorites auto-categories (subscribed, mod, etc.)

### ISSUE THREAD

**Issue by qs-arno** [Previews-app/Previews#38]
It would be nice to be able to have an "automatic favorites category" that's dynamically populated with channels I'm subscribed to.  When I get gifted a sub in a channel, I usually like to spend some time there while it's active.

Personally I'm interested in subscribed channels, but here are some other ideas for "auto-categories" that others might find useful:

- User is a moderator
- User is a VIP
- Specified list of categories
- Specified list of tags
- Specified text string in the title
- Twitch Drops enabled
- Active Hype Train

**Comment by Previews-app** [comment]
The extension doesn't use the twitch api so this is not possible.
