### ISSUE TITLE
Multi-chat compatibility with 7tv,BTTV and FrankerFaceZ

### ISSUE THREAD

**Issue by mlodystarzec1** [Previews-app/Previews#39]
It would be nice to add compatibility of multi-chat with 7tv, BTTV and FrankerFaceZ, cause i dont see any posibility to turn it on in settings. It would make usage of this addon more enjoyable. If you can you should add an option in settings to turn it on/off.
I can also help with the translation into Polish

**Comment by mlodystarzec1** [comment]
when i opened multi-chat i couldn't see any emotes from 7tv, BTTV and FrankerFaceZ, it's all about emotes in this case but 
now when I look at it, these emotes work, so I don't know, why they weren't working before, anyway the issue of missing emotes has ended for now

**Comment by Previews-app** [comment]
the multichat uses Twitch embeds, like: https://www.twitch.tv/embed/lacy/chat?darkpopout&parent=twitch.tv

you would have to ask the other extensions to fix it as it's not related to previews.
