### ISSUE TITLE
features dont work on embedded players

### ISSUE THREAD

**Issue by HamsterHawk** [Previews-app/Previews#4]
the youtube and twitch features dont work on embedded players

1. Go to https://www.destiny.gg/bigscreen#youtube/a5uQMwRMHcs

Expected behavior
there should be an option to use features like the flashbang defender

Screenshots and videos
https://i.imgur.com/FIG3G2m.png there is no option to use the flash bang feature

it might have to do with what sites have access to the extension, because the sponsor block extension shows up in embeds. https://i.imgur.com/mrSIqBb.png https://i.imgur.com/r6RbHdT.png those two pictures show the sponsorblock extension working on embedded players and what sites it has access to

and this picture shows what this extension has access to https://i.imgur.com/1MbxhFk.png

Environment
 - OS: Win 10
 - Browser: chrome
 - Browser Version: Version 110.0.5481.78 (Official Build) (32-bit)
 - Extension Version: 7.8

**Comment by Previews-app** [comment]
added flashbang defender and prevent click to pause and picture in picture in youtube embeds if they are enabled in 10.0, might add additionals in the future.
