### ISSUE TITLE
[Sidebar] Favourites not redirecting URL

### ISSUE THREAD

**Issue by robertow83** [Previews-app/Previews#40]
**Describe the bug**
When navigating to a favourite stream, the page redirect doesn't load. The URL updates to that of the clicked, but the stream will not change. This doesn't affect non-favourite channels, they will navigate as expected.

**To Reproduce**
1. Pin a followed channel to Favourite section
2. Click on a Favourite channel, either in a stream or not.
3. Plugin appends the Followed channel URL redirect with a '#' e.g. "https://www.twitch.tv/afavourite#" rather than "https://www.twitch.tv/afavourite"

**Expected behavior**
The plugin shouldn't append a '#' onto the Favourite Chanel redirect. As is the case when using the Sidebar to switch to another, non-Favourite channel.

**Environment:**
 - OS: Windows 11 (also observed in ChromeOS)
 - Browser: Firefox
 - Browser Version: 133.0 (64-bit)
 - Extension Version: 11.4

**Comment by Previews-app** [comment]
yep already fixed, duplicate, check [https://github.com/Previews-app/Previews/issues/37](https://github.com/Previews-app/Previews/issues/37)

**Comment by robertow83** [comment]
Great news. Apologies for not checking previous bug reports/fixes. Thank you.
