### ISSUE TITLE
YouTube Picture-in-Picture (Video Embed) "Add Multi-Chat" Chat Window Opacity

### ISSUE THREAD

**Issue by combativeThinker** [Previews-app/Previews#41]
**Describe the bug**
When clicking the "Add Multi-Chat" button on a YouTube livestream Picture-in-Picture popup, which was itself created from the left sidebar "Picture-in-Picture (Video Embed)" button, the chat feed window will be normal for a second or two, then the black background will disappear and it will become completely transparent, making reading the white text of the chat extremely difficult as the home page text for video titles etc. is white as well and will obscure whatever message is currently on top of it.

**To Reproduce**
1. Go to the YouTube home page.
2. Click on the "Picture-in-Picture (Video Embed)" button that appears when you mouse over a subscription livestream in the left sidebar. Then, once the Picture-in-Picture window for the stream has opened and started playing, mouse over the top of the player. There should be a button that displays the text "Add Multi-Chat" when moused over; click it.

**Expected behavior**
I expected a legible chat window to open that could be re-sized and re-positioned on the webpage, per the description of the feature on the extension's Mozilla Firefox Browser Add-Ons page. 

**Screenshots and videos**
If applicable, add screenshots and videos to help explain your problem.
Screenshots attached.
![chat opacity 1](https://github.com/user-attachments/assets/8501411c-5796-49c5-9a69-cb619e8e10d0)
"chat opacity 1" displays what the chat looks like for 1-2 seconds after clicking the "Add Multi-Chat" button at the top of the Picture-in-Picture window.
![chat opacity 2](https://github.com/user-attachments/assets/c9107ce2-8f8e-43c9-bda6-c736ae0720d7)
"chat opacity 2" displays what the chat looks like in perpetuity after the initial 1-2 seconds.

**Environment:**
 - OS: Windows 10 (ofc)
 - Browser: Firefox
 - Browser Version: 133.0 (64-bit)
 - Extension Version: 2.36.0.1
 - Was also using the "Tweaks for YouTube" extension (https://tinyurl.com/2z4484zb), version 3.73.0 -- link to settings: https://tinyurl.com/2k5uu5p7

**Additional context**

**Comment by Previews-app** [comment]
fixed for next version.
![image](https://github.com/user-attachments/assets/3cf0d791-73d1-422b-bb1c-0d0db04c903f)
