### ISSUE TITLE
[Feature Request] Add ability to remove react button

### ISSUE THREAD

**Issue by blackpoolfc04** [Previews-app/Previews#6]
Add the option to disable the "react" button below streams. 

It is a nuisance and is in the way. Not sure when it was added but it is annoying.
I have linked an image below showing it
![04 04 23_19 36 20   chrome   5899](https://user-images.githubusercontent.com/96628476/229887439-f0c254c9-c137-4524-aef3-87d947265d30.png)

**Comment by Previews-app** [comment]
seems like an issue with your client, it shouldn't overlap, check your extensions or custom stuff if you added any, maybe clear cache i dunno.

**Comment by blackpoolfc04** [comment]
@Previews-app Ahhh. Found the issue. It was the Frankerz Face hide follow/unfollow button option. A similar option in this extension would be good tbh.
