### ISSUE TITLE
My autorefresher is not working and i would like to know how to fix it

### ISSUE THREAD

**Issue by Corenana** [Previews-app/Previews#7]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots and videos**
If applicable, add screenshots and videos to help explain your problem.

**Environment:**
 - OS: [e.g. Windows 10]
 - Browser: [e.g. chrome, firefox]
 - Browser Version:
 - Extension Version: 
 - <any other variables you may see fit>

**Additional context**

**Comment by Previews-app** [comment]
Fixed in 8.0.
