### ISSUE TITLE
Nothing Working

### ISSUE THREAD

**Issue by ufos8mycow** [Previews-app/Previews#8]
**Describe the bug**
The App is completely broken. I can't see any previews. No functionality from any of the apps bonus features. Clicking on the Preview App Menu button on top right does nothing but cause a second or two of lag with the mouse/browser. I've tried deleting/reinstalling/updating with no joy.

**To Reproduce**
1- Open Twitch
2- Click anything related to this App
3- Attempt to use App

**Expected behavior**
Menu opening, previews showing, etc

**Environment:**
 - OS: Windows 10
 - Browser: Firefox
 - Browser Version: 111.0.1 (64-bit)
 - Extension Version: 7.9

**Comment by Previews-app** [comment]
Sshould be fixed in 8.0.
